;; An example failing computation, to exercise the debugger.
;; This turned into essentially a repeat of test-continuations.scm.

(import ((use 'traceback) (export out))
  on-error-traceback)

(to (factorial n)
  (if (= 0 n)
      (error "I don't know 0!")
      (* n (factorial (- n 1)))))

(to (on-error-complain-and-continue sequel evil)
  (on-error-traceback sequel evil)
  (out .display "About to continue with 10\n")
  (the-signal-handler .^= on-error-traceback) ;; Restore the usual handler.
  (sequel .answer 10))

(the-signal-handler .^= on-error-complain-and-continue)
(out .print (factorial 5))
